
server:
    port: 8090
    
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;
    username: 
    password: 
    driverClassName: org.h2.Driver
  jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: true
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
            show_sql : false
            format_sql : false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.hbm2ddl.auto: update
  
  
