server:
    port: 8090
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
    username: 'sa'
    password: 
    driverClassName: org.h2.Driver
  flyway:
   enabled: true
   check-location: true
   baselineOnMigrate: true
   validateOnMigrate: false
   url: jdbc:h2:file:./data.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
   locations: classpath:db/migration
   user: 'sa'
   password: 
  