spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
   enabled: true
   baselineOnMigrate: true
   url: jdbc:mysql://localhost:3306/flywaytest?createDatabaseIfNotExist=true
   locations: classpath:/db/migration
   user: "root"
   password: "P@ssw0rd"
  